# Slack app credentials
# Provide these via ENV: SLACK_CLIENT_ID, SLACK_CLIENT_SECRET, SLACK_SIGNING_SECRET
SLACK_CLIENT_ID = ENV['SLACK_CLIENT_ID']
SLACK_CLIENT_SECRET = ENV['SLACK_CLIENT_SECRET']
SLACK_SIGNING_SECRET = ENV['SLACK_SIGNING_SECRET']
