class Address < ApplicationRecord
  belongs_to :user
  has_many :orders

  enum :country, {
    "US - United States": 0,
    "CA - Canada": 1,
    "GB - United Kingdom": 2,
    "MX - Mexico": 3,
    "BR - Brazil": 4,
    "AR - Argentina": 5,
    "CL - Chile": 6,
    "CO - Colombia": 7,
    "PE - Peru": 8,
    "DE - Germany": 9,
    "FR - France": 10,
    "ES - Spain": 11,
    "IT - Italy": 12,
    "PT - Portugal": 13,
    "NL - Netherlands": 14,
    "BE - Belgium": 15,
    "CH - Switzerland": 16,
    "AT - Austria": 17,
    "SE - Sweden": 18,
    "NO - Norway": 19,
    "DK - Denmark": 20,
    "FI - Finland": 21,
    "IE - Ireland": 22,
    "PL - Poland": 23,
    "CZ - Czech Republic": 24,
    "RU - Russia": 25,
    "UA - Ukraine": 26,
    "CN - China": 27,
    "JP - Japan": 28,
    "KR - South Korea": 29,
    "IN - India": 30,
    "AU - Australia": 31,
    "NZ - New Zealand": 32,
    "ZA - South Africa": 33,
    "NG - Nigeria": 34,
    "EG - Egypt": 35,
    "AE - United Arab Emirates": 36,
    "SA - Saudi Arabia": 37,
    "IL - Israel": 38,
    "TR - Turkey": 39,
    "TH - Thailand": 40,
    "VN - Vietnam": 41,
    "PH - Philippines": 42,
    "ID - Indonesia": 43,
    "MY - Malaysia": 44,
    "SG - Singapore": 45
  }
end
